type FormDraft {
  Id: ID
  Name: String
  Rules: [FormRule]
  SuccessMessage: String
  Title: String
  AvailableActions: [AvailableAction]
  Fields: [FormField]
  LastModified: Datetime
  Provider: String
  Steps: [Step]
}

input FormDraftInput {
  AvailableActions: [AvailableAction]
  Fields: [FormField]
  LastModified: Datetime
  Provider: String
  Steps: [Step]
  Id: String
  Name: String
  Rules: [FormRule]
  SuccessMessage: String
  Title: String
}

type ComponentsResponse {
  Components: [ComponentDto]
}

type HierarchicalTaxon {
  Provider: String
  Title: String
  UrlName: String
  FullUrl: String
  LastModified: Datetime
  Ordinal: Float
  Name: String
  ParentId: String
  Synonyms: String
  TaxonomyId: String
  AppliedTo: Int
  Description: String
  Id: ID
}

input HierarchicalTaxonInput {
  AppliedTo: Int
  Description: String
  Id: String
  Name: String
  ParentId: String
  Synonyms: String
  TaxonomyId: String
  FullUrl: String
  LastModified: Datetime
  Ordinal: Float
  Provider: String
  Title: String
  UrlName: String
}

type PropertyValueContainer {
  Name: String
  Value: String
}

type PropertyValueGroupContainer {
  Properties: [PropertyValueContainer]
  PropertyLocalizationMode: String
  PropertyMetadata: [PropertyContainer]
  Caption: String
  ComponentId: String
}

type ParentTemplate {
  Renderer: String
  Title: String
  Id: String
}

type Void {
}

type ThumbnailModel {
  Width: Int
  Height: Int
  MimeType: String
  Title: String
  Url: String
}

enum ServiceHookActivityStatus {
  Failed @meta(value: 2, valueType: int32)
  Pending @meta(value: 0, valueType: int32)
  Running @meta(value: 1, valueType: int32)
  Successful @meta(value: 3, valueType: int32)
}

type ChoiceValue {
  Name: String
  Title: String
  Value: String
}

type AvailableAction {
  Key: FormRuleAction
  Value: String
}

type Showcase {
  Solution: String
  IncludeInSitemap: Boolean
  PublicationDate: Datetime
  Title: String
  Website: String
  Client: String
  Thumbnail: Image
  DateCreated: Datetime
  LastModified: Datetime
  Results: String
  UrlName: String
  Category: [String]
  Challenge: String
  ItemDefaultUrl: String
  Provider: String
  Tags: [String]
  Download: Document
  Id: ID
}

input ShowcaseInput {
  Id: String
  ItemDefaultUrl: String
  Provider: String
  Tags: [String]
  IncludeInSitemap: Boolean
  PublicationDate: Datetime
  Solution: String
  Client: String
  Title: String
  Website: String
  Category: [String]
  Challenge: String
  DateCreated: Datetime
  LastModified: Datetime
  Results: String
  UrlName: String
}

type RendererData {
  HostHeaderName: String
  IdentityServerHostHeaderValue: String
  SitefinityUrl: String
  Url: String
  WebService: String
  AuthRedirectUrl: String
}

type EditorState {
  AddAllowed: Boolean
  EditAllowed: Boolean
  HasChanged: Boolean
  SegmentId: String
  Version: Int
  WidgetState: [WidgetState]
}

enum TaxonomyType {
  Flat @meta(value: 0, valueType: int32)
  Hierarchical @meta(value: 1, valueType: int32)
}

type TemplateStatistic {
  Count: Int
  Name: String
}

type RuleAction {
  Target: String
  Action: FormRuleAction
}

type Folder {
  RootId: String
  Title: String
  ParentId: String
  ChildrenCount: Int
  FoldersCount: Int
  Id: String
  ImagesUrl: [String]
  LastModified: Datetime
  Breadcrumb: [String]
}

type OperationCategory {
  Name: String
  Title: String
}

type LockContext {
  Version: Int
}

type SharedInSiteModel {
  Id: String
  IsShared: Boolean
  Name: String
}

type SiteConfiguration {
  LiveUrl: String
  IsDefaultSite: Boolean
}

type FieldSettings {
  Key: String
  AllowCreate: Boolean
  AllowView: Boolean
}

type DataProviderModel {
  isDefault: Boolean
  name: String
  title: String
}

type Event {
  ContactWeb: String
  Title: String
  DateCreated: Datetime
  EventEndUtcOffset: Float
  Id: ID
  IncludeInSitemap: Boolean
  LastModified: Datetime
  Provider: String
  State: String
  TimeZoneId: String
  AllDayEvent: Boolean
  Description: String
  EventStart: Datetime
  RecurrenceExpression: String
  Comments: [CommentContract]
  EventStartUtcOffset: Float
  Parent: Calendar
  ParentId: String
  ContactName: String
  EventEndWithOffset: Datetime
  ItemDefaultUrl: String
  Category: [String]
  City: String
  ContactCell: String
  Content: String
  EventStartWithOffset: Datetime
  Location: String
  Street: String
  Summary: String
  Tags: [String]
  AllowComments: Boolean
  ContactEmail: String
  ContactPhone: String
  Country: String
  EventEnd: Datetime
  IsRecurrent: Boolean
  PublicationDate: Datetime
  UrlName: String
}

input EventInput {
  ContactPhone: String
  Country: String
  EventEnd: Datetime
  IsRecurrent: Boolean
  PublicationDate: Datetime
  UrlName: String
  AllowComments: Boolean
  ContactEmail: String
  ContactWeb: String
  Title: String
  Id: String
  IncludeInSitemap: Boolean
  LastModified: Datetime
  Provider: String
  State: String
  TimeZoneId: String
  DateCreated: Datetime
  EventEndUtcOffset: Float
  EventStart: Datetime
  RecurrenceExpression: String
  AllDayEvent: Boolean
  Description: String
  ParentId: String
  Comments: [CommentContract]
  EventStartUtcOffset: Float
  ItemDefaultUrl: String
  ContactName: String
  EventEndWithOffset: Datetime
  ContactCell: String
  Content: String
  EventStartWithOffset: Datetime
  Location: String
  Street: String
  Summary: String
  Category: [String]
  City: String
  Tags: [String]
}

type DisplayStatus {
  ExpirationDate: Datetime
  Id: String
  Message: Message
  User: String
  DetailedLabel: String
  Label: String
  Name: String
  PublicationDate: Datetime
  Source: String
  Date: Datetime
}

type BlogPost {
  AllowComments: Boolean
  DateCreated: Datetime
  Id: ID
  LastModified: Datetime
  Provider: String
  Summary: String
  Comments: [CommentContract]
  PublicationDate: Datetime
  Category: [String]
  UrlName: String
  Content: String
  Description: String
  IncludeInSitemap: Boolean
  ItemDefaultUrl: String
  Parent: Blog
  ParentId: String
  Tags: [String]
  Title: String
}

input BlogPostInput {
  Tags: [String]
  Title: String
  Content: String
  Description: String
  IncludeInSitemap: Boolean
  ItemDefaultUrl: String
  ParentId: String
  AllowComments: Boolean
  DateCreated: Datetime
  Id: String
  LastModified: Datetime
  Provider: String
  Summary: String
  Comments: [CommentContract]
  PublicationDate: Datetime
  Category: [String]
  UrlName: String
}

type Blog {
  ItemDefaultUrl: String
  PublicationDate: Datetime
  Title: String
  Description: String
  Id: ID
  IncludeInSitemap: Boolean
  UrlName: String
  DateCreated: Datetime
  LastModified: Datetime
  Provider: String
}

input BlogInput {
  DateCreated: Datetime
  LastModified: Datetime
  Provider: String
  UrlName: String
  Title: String
  Description: String
  Id: String
  IncludeInSitemap: Boolean
  ItemDefaultUrl: String
  PublicationDate: Datetime
}

type FilterParameters {
}

enum NotificationType {
  Error @meta(value: 2, valueType: int32)
  None @meta(value: 0, valueType: int32)
  Success @meta(value: 1, valueType: int32)
  Warning @meta(value: 3, valueType: int32)
}

type SiteConfigurationViewModel {
  DataSources: [SiteDataSourceConfigViewModel]
  DomainAliases: [String]
  IsAllowedStartStop: Boolean
  IsCurrentSite: Boolean
  IsDefault: Boolean
  RequiresSsl: Boolean
  SourcePagesSiteId: String
  StagingUrl: String
  HomePageId: String
  Id: String
  LiveUrl: String
  OfflinePageToRedirect: String
  PublicContentCultures: [CultureViewModel]
  RedirectIfOffline: Boolean
  SystemCultures: [CultureViewModel]
  FrontEndLoginPageId: String
  IsOffline: Boolean
  OfflineSiteMessage: String
  UseSystemCultures: Boolean
  FrontEndLoginPageUrl: String
  Name: String
  SiteConfigurationMode: SiteConfigurationMode
  SiteMapRootNodeId: String
}

type SitemapPage {
  Children: [SitemapPage]
  LastModified: Datetime
  LastModifiedBy: String
  PageType: PageType
  Title: String
  ParentId: String
  Renderer: String
  CreatedBy: String
  DateCreated: Datetime
  DisplayStatus: [DisplayStatus]
  EditUrl: String
  Id: String
  AvailableLanguages: [String]
  BreadCrumb: [String]
  LockedStatus: ItemEventInfo
  Marketing: MarketingPropertyValue
  ViewUrl: String
  HasChildren: Boolean
  IsHomePage: Boolean
}

type AnalyticsSettingsDto {
  Configured: Boolean
  Installed: Boolean
  ItemSupport: Boolean
}

type Address {
  City: String
  CountryCode: String
  Id: String
  Latitude: Float
  Longitude: Float
  StateCode: String
  MapZoomLevel: Int
  Street: String
  Zip: String
}

enum SiteConfigurationMode {
  ConfigureManually @meta(value: 0, valueType: int32)
  ConfigureByDeployment @meta(value: 1, valueType: int32)
}

enum BulkOperationResultType {
  Error @meta(value: 2, valueType: int32)
  Success @meta(value: 0, valueType: int32)
  Warning @meta(value: 1, valueType: int32)
}

type Section {
  Name: String
  Properties: [PropertyContainer]
  Title: String
}

type BreadcrumbItem {
  FolderId: String
  Title: String
}

enum ConditionOperator {
  IsLessThan @meta(value: 6, valueType: int32)
  NotEqual @meta(value: 1, valueType: int32)
  FileSelected @meta(value: 8, valueType: int32)
  IsGreaterThan @meta(value: 7, valueType: int32)
  FileNotSelected @meta(value: 9, valueType: int32)
  IsFilled @meta(value: 4, valueType: int32)
  IsNotFilled @meta(value: 5, valueType: int32)
  NotContains @meta(value: 3, valueType: int32)
  Contains @meta(value: 2, valueType: int32)
  Equal @meta(value: 0, valueType: int32)
}

type FormDescription {
  Rules: String
  DateCreated: Datetime
  Provider: String
  PublicationDate: Datetime
  Tags: [String]
  Title: String
  Id: ID
  IncludeInSitemap: Boolean
  LastModified: Datetime
  Name: String
  SuccessMessage: String
  Category: [String]
  Description: String
  DisplayStatus: [DisplayStatus]
}

input FormDescriptionInput {
  Id: String
  IncludeInSitemap: Boolean
  Category: [String]
  Description: String
  DisplayStatus: [DisplayStatus]
  LastModified: Datetime
  Name: String
  SuccessMessage: String
  DateCreated: Datetime
  Provider: String
  PublicationDate: Datetime
  Rules: String
  Tags: [String]
  Title: String
}

type List {
  PublicationDate: Datetime
  SortOrder: String
  Id: ID
  LastModified: Datetime
  Provider: String
  Title: String
  UrlName: String
  DateCreated: Datetime
  Description: String
  IncludeInSitemap: Boolean
}

input ListInput {
  LastModified: Datetime
  Provider: String
  PublicationDate: Datetime
  SortOrder: String
  Id: String
  Description: String
  IncludeInSitemap: Boolean
  Title: String
  UrlName: String
  DateCreated: Datetime
}

type ExtendedMediaLink {
  NumberOfChunks: Int
  Url: String
  Culture: Int
  DefaultUrl: String
  Id: String
  MimeType: String
  Height: Int
  MediaContentId: String
  ThumbnailUrl: String
  Cultures: [String]
  FilePath: String
  MediaFileUrlName: String
  Width: Int
  Title: String
  TotalSize: Int
  ApplicationName: String
  ChunkSize: Int
  Extension: String
  FileId: String
}

type WidgetOperationResult {
  SucceededItemsIds: [String]
  Success: Boolean
  Title: String
  AvailableActions: [String]
  FailedItemsIds: [String]
  MultipleItemsMessage: String
  Properties: [PropertyValueContainer]
  State: WidgetState
  Type: NotificationType
  UndoOperation: ItemOperation
  Link: String
  Message: String
}

enum TaskStatus {
  Pending @meta(value: 0, valueType: int32)
  Started @meta(value: 1, valueType: int32)
  Stopped @meta(value: 3, valueType: int32)
  Failed @meta(value: 2, valueType: int32)
}

type PublicationInfo {
  Date: Datetime
  User: String
}

enum AddressFieldMode {
  FormOnly @meta(value: 0, valueType: int32)
  Hybrid @meta(value: 2, valueType: int32)
  MapOnly @meta(value: 1, valueType: int32)
}

enum FormRuleAction {
  Skip @meta(value: 2, valueType: int32)
  GoTo @meta(value: 3, valueType: int32)
  Hide @meta(value: 1, valueType: int32)
  SendNotification @meta(value: 5, valueType: int32)
  Show @meta(value: 0, valueType: int32)
  ShowMessage @meta(value: 4, valueType: int32)
}

type CountryModel {
  states: [StateModel]
  hasStates: Boolean
  isoCode: String
  name: String
}

type Author {
  Name: String
  Avatar: Image
  DateCreated: Datetime
  IncludeInSitemap: Boolean
  JobTitle: String
  LastModified: Datetime
  Provider: String
  PublicationDate: Datetime
  UrlName: String
  Bio: String
  Id: ID
  ItemDefaultUrl: String
}

input AuthorInput {
  Provider: String
  PublicationDate: Datetime
  UrlName: String
  Bio: String
  Id: String
  ItemDefaultUrl: String
  JobTitle: String
  LastModified: Datetime
  DateCreated: Datetime
  IncludeInSitemap: Boolean
  Name: String
}

enum ContentLifecycleStatus {
  Deleted @meta(value: 4, valueType: int32)
  Live @meta(value: 2, valueType: int32)
  Master @meta(value: 0, valueType: int32)
  PartialTemp @meta(value: 8, valueType: int32)
  Temp @meta(value: 1, valueType: int32)
}

type PageNode {
  CanonicalUrlBehaviour: CanonicalUrlSettings
  Crawlable: Boolean
  EditUrl: String
  HasChildren: Boolean
  LastModified: Datetime
  OutputCacheProfile: String
  ParentId: String
  ViewUrl: String
  Description: String
  HtmlTitle: String
  IncludeInSearchIndex: Boolean
  IsHomePage: Boolean
  PublicationDate: Datetime
  ShowInNavigation: Boolean
  Title: String
  AvailableLanguages: [String]
  DateCreated: Datetime
  IncludeScriptManager: Boolean
  Priority: Float
  Provider: String
  TemplateId: String
  Breadcrumb: [String]
  HeadTagContent: String
  RelativeUrlPath: String
  Renderer: String
  RequireSsl: Boolean
  UrlName: String
  Id: ID
  PageType: PageType
  RootId: String
  AllowParametersValidation: Boolean
  CodeBehindType: String
  Image: Image
  LocalizationStrategy: LocalizationStrategy
  RedirectPage: RedirectPage
  TemplateName: String
  EnableViewState: Boolean
}

input PageNodeInput {
  EnableViewState: Boolean
  LastModified: Datetime
  OutputCacheProfile: String
  CanonicalUrlBehaviour: CanonicalUrlSettings
  Crawlable: Boolean
  EditUrl: String
  HasChildren: Boolean
  ParentId: String
  PublicationDate: Datetime
  ShowInNavigation: Boolean
  Title: String
  ViewUrl: String
  Description: String
  HtmlTitle: String
  IncludeInSearchIndex: Boolean
  IsHomePage: Boolean
  Provider: String
  TemplateId: String
  AvailableLanguages: [String]
  DateCreated: Datetime
  IncludeScriptManager: Boolean
  Priority: Float
  RequireSsl: Boolean
  UrlName: String
  Breadcrumb: [String]
  HeadTagContent: String
  RelativeUrlPath: String
  Renderer: String
  Id: String
  PageType: PageType
  RootId: String
  RedirectPage: RedirectPage
  TemplateName: String
  AllowParametersValidation: Boolean
  CodeBehindType: String
  LocalizationStrategy: LocalizationStrategy
}

type DiagnosticsDto {
  Name: String
  Success: Boolean
  HelpLink: String
  Message: String
}

type DefaultExecuteOperationContext {
  Parameters: [PropertyValueContainer]
  PropertyMetadata: [PropertyContainer]
  WidgetKey: String
  WidgetSegmentId: String
  ActionName: String
  Name: String
}

type PageScript {
  Value: String
  Attributes: [PageScriptAttribute]
  Source: String
}

type TaxonDTO {
  Id: String
  LastModified: Datetime
  Name: String
  TaxonomyId: String
  Title: String
  UrlName: String
  AvailableLanguages: [String]
  Description: String
}

enum CanonicalUrlSettings {
  Default @meta(value: 0, valueType: int32)
  Disabled @meta(value: 1, valueType: int32)
  Enabled @meta(value: 2, valueType: int32)
}

type Calendar {
  ExpirationDate: Datetime
  Id: ID
  PublicationDate: Datetime
  Title: String
  Color: String
  DateCreated: Datetime
  Description: String
  LastModified: Datetime
  Provider: String
  UrlName: String
}

input CalendarInput {
  Color: String
  DateCreated: Datetime
  Description: String
  LastModified: Datetime
  Provider: String
  UrlName: String
  ExpirationDate: Datetime
  Id: String
  PublicationDate: Datetime
  Title: String
}

type FormField {
  InputType: String
  Operators: [Operator]
  Title: String
  Type: String
  Values: [String]
  Hideable: Boolean
  Id: String
}

type SectionGroup {
  Name: String
  Sections: [Section]
}

type OperationParameter {
  Name: String
  Tooltip: String
  Value: String
  Arguments: [ParameterArgument]
  FriendlyTitle: String
  Hint: String
  Placeholder: String
  Required: Boolean
  Title: String
  Type: String
}

type DefaultAddWidgetContext {
  SiblingKey: String
  Id: String
  Name: String
  ParentPlaceholderKey: String
  PlaceholderName: String
  Properties: [PropertyValueContainer]
}

type HierarchicalWidgetModelResponse {
  WidgetState: [WidgetState]
  Lazy: Boolean
  Name: String
  Properties: PropertiesModel
  SiblingId: String
  ViewName: String
  Caption: String
  Children: [ComponentDto]
  Id: String
  PlaceHolder: String
}

type ServiceHookSettingChoice {
  ParametersMetadata: [Section]
  Priority: Float
  Value: String
  Module: String
  Name: String
}

type FrontendSitemapPage {
  AvailableLanguages: [String]
  BreadCrumb: [String]
  Id: String
  IsHomePage: Boolean
  Title: String
  ViewUrl: String
  Children: [FrontendSitemapPage]
  HasChildren: Boolean
  PageType: PageType
  ParentId: String
}

type TypeInfo {
  ProviderDisplayName: String
  DisplayName: String
}

type AnalyticsDto {
  AnalyticsUrl: String
  Id: String
}

type VideoLibrary {
  BlobStorageProvider: String
  ChildrenCount: Int
  ItemDefaultUrl: String
  LastModified: Datetime
  MaxSize: Int
  DateCreated: Datetime
  Id: ID
  OutputCacheProfile: String
  ClientCacheProfile: String
  CoverId: String
  MaxItemSize: Int
  Provider: String
  PublicationDate: Datetime
  Title: String
  Description: String
  IncludeInSitemap: Boolean
  ParentId: String
  ThumbnailProfiles: [String]
  UrlName: String
}

input VideoLibraryInput {
  Description: String
  IncludeInSitemap: Boolean
  ParentId: String
  ThumbnailProfiles: [String]
  UrlName: String
  BlobStorageProvider: String
  ChildrenCount: Int
  ItemDefaultUrl: String
  LastModified: Datetime
  MaxSize: Int
  DateCreated: Datetime
  Id: String
  OutputCacheProfile: String
  ClientCacheProfile: String
  CoverId: String
  MaxItemSize: Int
  Provider: String
  PublicationDate: Datetime
  Title: String
}

type ExtendedFolder {
  Breadcrumb: [BreadcrumbItem]
  PreviewItems: [MediaContent]
  RunningTask: String
  Storage: String
  Title: String
  TotalLibrarySizeInKb: Int
  ParentId: String
  RootId: String
  Description: String
  FoldersCount: Int
  LastUploadedBy: String
  ChildrenCount: Int
  Id: String
  LastUploaded: Datetime
  MaxLibrarySizeInKb: Int
}

type Site {
  Provider: String
  CulturesMap: [CultureModel]
  DefaultCultureKey: String
  DefaultFrontendTemplateId: String
  Id: ID
  IsOffline: Boolean
  CultureKeys: [String]
  LiveUrl: String
  Name: String
  SiteMapRootNodeId: String
}

input SiteInput {
  CulturesMap: [CultureModel]
  DefaultCultureKey: String
  DefaultFrontendTemplateId: String
  Id: String
  IsOffline: Boolean
  Provider: String
  CultureKeys: [String]
  LiveUrl: String
  Name: String
  SiteMapRootNodeId: String
}

type SiteDataSourceLinkViewModel {
  ProviderName: String
  ProviderTitle: String
  SiteId: String
  DataSourceName: String
  Id: String
  IsDefault: Boolean
  IsGlobalProvider: Boolean
}

type ControlMetadata {
  Caption: String
  Name: String
  PropertyMetadata: [SectionGroup]
  PropertyMetadataFlat: [PropertyContainer]
  ViewName: String
}

type DocumentLibrary {
  ItemDefaultUrl: String
  LastModified: Datetime
  CoverId: String
  Description: String
  PublicationDate: Datetime
  BlobStorageProvider: String
  ChildrenCount: Int
  ClientCacheProfile: String
  MaxSize: Int
  OutputCacheProfile: String
  ParentId: String
  Id: ID
  IncludeInSitemap: Boolean
  MaxItemSize: Int
  Title: String
  UrlName: String
  DateCreated: Datetime
  Provider: String
  ThumbnailProfiles: [String]
}

input DocumentLibraryInput {
  Id: String
  IncludeInSitemap: Boolean
  MaxItemSize: Int
  MaxSize: Int
  OutputCacheProfile: String
  ParentId: String
  DateCreated: Datetime
  Provider: String
  ThumbnailProfiles: [String]
  Title: String
  UrlName: String
  ItemDefaultUrl: String
  LastModified: Datetime
  BlobStorageProvider: String
  ChildrenCount: Int
  ClientCacheProfile: String
  CoverId: String
  Description: String
  PublicationDate: Datetime
}

type MediaContent {
  Version: Int
  AllowComments: Boolean
  ApproveComments: Boolean
  BlobStorageProvider: String
  ItemDefaultUrl: Lstring
  Owner: String
  TotalSize: Int
  Description: Lstring
  EmbedUrl: String
  Id: String
  IncludeInSitemap: Boolean
  Status: ContentLifecycleStatus
  VotesCount: Int
  ApprovalWorkflowState: Lstring
  EmailAuthor: Boolean
  MediaFileUrlName: Lstring
  PostRights: PostRights
  DateCreated: Datetime
  ParentId: String
  ThumbnailNames: [String]
  Visible: Boolean
  AllowTrackBacks: Boolean
  Author: Lstring
  DefaultPageId: String
  OriginalContentId: String
  UIStatus: ContentUIStatus
  ViewsCount: Int
  MediaUrl: String
  UrlName: Lstring
  VotesSum: Decimal
  AvailableLanguages: [String]
  Extension: String
  ThumbnailUrl: String
  ExpirationDate: Datetime
  FolderId: String
  LastModifiedBy: String
  PublicationDate: Datetime
  Title: Lstring
}

type Taxonomy {
  Name: String
  RootTaxonomyId: String
  TaxaUrl: String
  TaxonomySharedWith: Int
  Title: String
  Type: TaxonomyType
  Description: String
  LastModified: Datetime
  Id: ID
  TaxonName: String
  DefaultTaxonName: String
  DefaultTitle: String
}

input TaxonomyInput {
  Name: String
  RootTaxonomyId: String
  TaxaUrl: String
  TaxonomySharedWith: Int
  Title: String
  Type: TaxonomyType
  Description: String
  LastModified: Datetime
  Id: String
  TaxonName: String
  DefaultTaxonName: String
  DefaultTitle: String
}

type Result {
  Description: String
  ImageUrl: String
  Key: String
  Title: String
}

type RuleCondition {
  Value: String
  Id: String
  Operator: ConditionOperator
}

type OperationAction {
  Name: String
  Title: String
  Type: Int
}

type PageTemplate {
  Framework: PageTemplateFramework
  Id: ID
  Provider: String
  Renderer: String
  ThumbnailUrl: String
  Title: String
  Thumbnail: String
  DateCreated: Datetime
  LastModified: Datetime
  Name: String
  ParentTemplate: ParentTemplate
  TemplateId: String
  TemplateName: String
}

input PageTemplateInput {
  Id: String
  Provider: String
  Renderer: String
  ThumbnailUrl: String
  Title: String
  Framework: PageTemplateFramework
  LastModified: Datetime
  Name: String
  ParentTemplate: ParentTemplate
  TemplateId: String
  TemplateName: String
  Thumbnail: String
  DateCreated: Datetime
}

type ReorderAction {
  Id: String
  Position: ReorderPosition
  TargetId: String
}

type RelatedSiteInfo {
  Name: String
  Url: String
}

type ListItem {
  Category: [String]
  Description: String
  Ordinal: Float
  ParentId: String
  Provider: String
  Title: String
  Id: ID
  LastModified: Datetime
  Parent: List
  PublicationDate: Datetime
  UrlName: String
  Content: String
  DateCreated: Datetime
  IncludeInSitemap: Boolean
  Tags: [String]
}

input ListItemInput {
  Content: String
  DateCreated: Datetime
  IncludeInSitemap: Boolean
  Tags: [String]
  Category: [String]
  Description: String
  Ordinal: Float
  ParentId: String
  Provider: String
  Title: String
  Id: String
  LastModified: Datetime
  PublicationDate: Datetime
  UrlName: String
}

type ThumbnailModel {
  Size: String
  Title: String
  Url: String
}

type StateModel {
  countryKey: String
  stateProvinceName: String
  abbreviation: String
}

type ParameterizedSetting {
  Name: String
  Parameters: PropertiesModel
  Value: String
}

type Video {
  MimeType: String
  TotalSize: Int
  Category: [String]
  Description: String
  Extension: String
  ItemDefaultUrl: String
  ParentId: String
  PublicationDate: Datetime
  ThumbnailUrl: String
  Title: String
  Author: String
  FolderId: String
  LastModified: Datetime
  Parent: VideoLibrary
  Width: Int
  Tags: [String]
  Url: String
  Height: Int
  Id: ID
  IncludeInSitemap: Boolean
  Ordinal: Float
  DateCreated: Datetime
  Provider: String
  UrlName: String
}

input VideoInput {
  UrlName: String
  DateCreated: Datetime
  Provider: String
  Extension: String
  ItemDefaultUrl: String
  MimeType: String
  TotalSize: Int
  Category: [String]
  Description: String
  LastModified: Datetime
  ParentId: String
  PublicationDate: Datetime
  ThumbnailUrl: String
  Title: String
  Author: String
  FolderId: String
  Width: Int
  IncludeInSitemap: Boolean
  Ordinal: Float
  Tags: [String]
  Url: String
  Height: Int
  Id: String
}

type FlatTaxon {
  TaxonomyId: String
  Title: String
  UrlName: String
  Description: String
  Name: String
  Ordinal: Float
  Provider: String
  Synonyms: String
  AppliedTo: Int
  Id: ID
  LastModified: Datetime
}

input FlatTaxonInput {
  AppliedTo: Int
  Id: String
  LastModified: Datetime
  Provider: String
  Synonyms: String
  Description: String
  Name: String
  Ordinal: Float
  TaxonomyId: String
  Title: String
  UrlName: String
}

type Owner {
  FullName: String
  Id: String
  ImageUrl: String
  UserEmail: String
}

type Album {
  ItemDefaultUrl: String
  UrlName: String
  BlobStorageProvider: String
  CoverId: String
  IncludeInSitemap: Boolean
  MaxSize: Int
  Provider: String
  ResizeOnUpload: Boolean
  ThumbnailProfiles: [String]
  Title: String
  Id: ID
  LastModified: Datetime
  MaxItemSize: Int
  ParentId: String
  PublicationDate: Datetime
  ClientCacheProfile: String
  DateCreated: Datetime
  OutputCacheProfile: String
  ChildrenCount: Int
  Description: String
  NewSize: String
}

input AlbumInput {
  ChildrenCount: Int
  Description: String
  NewSize: String
  BlobStorageProvider: String
  CoverId: String
  IncludeInSitemap: Boolean
  ItemDefaultUrl: String
  UrlName: String
  ThumbnailProfiles: [String]
  Title: String
  Id: String
  LastModified: Datetime
  MaxItemSize: Int
  MaxSize: Int
  Provider: String
  ResizeOnUpload: Boolean
  ClientCacheProfile: String
  DateCreated: Datetime
  OutputCacheProfile: String
  ParentId: String
  PublicationDate: Datetime
}

type FormRule {
  Actions: [RuleAction]
  Conditions: [RuleCondition]
  Operator: LogicalOperator
}

type ComponentDto {
  Caption: String
  Children: [ComponentDto]
  Id: String
  PlaceHolder: String
  ViewName: String
  Lazy: Boolean
  Name: String
  Properties: PropertiesModel
  SiblingId: String
}

type PageDtoWithContext {
  ComponentContext: ComponentContext
  Culture: String
  DetailItem: ResolvedDetailItem
  Id: String
  Scripts: [PageScript]
  SiteId: String
  TemplateName: String
  UrlParameters: [String]
}

type Image {
  UrlName: String
  Category: [String]
  Id: ID
  Parent: Album
  ThumbnailUrl: String
  Title: String
  Url: String
  AlternativeText: String
  DateCreated: Datetime
  IncludeInSitemap: Boolean
  FolderId: String
  ItemDefaultUrl: String
  Provider: String
  PublicationDate: Datetime
  Tags: [String]
  Width: Int
  Ordinal: Float
  ParentId: String
  Author: String
  Description: String
  Extension: String
  Height: Int
  LastModified: Datetime
  MimeType: String
  Thumbnails: [ThumbnailModel]
  TotalSize: Int
}

input ImageInput {
  Provider: String
  PublicationDate: Datetime
  Tags: [String]
  Width: Int
  FolderId: String
  ItemDefaultUrl: String
  Extension: String
  Height: Int
  LastModified: Datetime
  MimeType: String
  Ordinal: Float
  ParentId: String
  Author: String
  Description: String
  Thumbnails: [ThumbnailModel]
  TotalSize: Int
  ThumbnailUrl: String
  Title: String
  Url: String
  UrlName: String
  Category: [String]
  Id: String
  IncludeInSitemap: Boolean
  AlternativeText: String
  DateCreated: Datetime
}

type Lstring {
  PersistedValue: String
  Value: String
}

type WidgetState {
  DeleteAllowed: Boolean
  EditAllowed: Boolean
  IsPersonalized: Boolean
  Key: String
  LabelTooltip: String
  MoveAllowed: Boolean
  Name: String
  WidgetSegmentId: String
}

type WcfScheduledTask {
  ConcurrentTaskKey: String
  Description: String
  Id: String
  Status: TaskStatus
  TaskData: String
  IsManageable: Boolean
  ProgressStatus: Int
  StatusMessage: String
  TaskName: String
  Title: String
}

type RedirectPage {
  NodeId: String
  OpenInNewWindow: Boolean
  ProviderName: String
  RedirectUrl: String
}

type Testimonial {
  JobTitle: String
  Provider: String
  TestimonialAuthor: String
  UrlName: String
  Company: String
  DateCreated: Datetime
  ItemDefaultUrl: String
  Quote: String
  Id: ID
  IncludeInSitemap: Boolean
  Photo: Image
  LastModified: Datetime
  PublicationDate: Datetime
  Title: String
}

input TestimonialInput {
  Id: String
  IncludeInSitemap: Boolean
  Title: String
  LastModified: Datetime
  PublicationDate: Datetime
  TestimonialAuthor: String
  UrlName: String
  JobTitle: String
  Provider: String
  ItemDefaultUrl: String
  Quote: String
  Company: String
  DateCreated: Datetime
}

type ValidationRequest {
}

type MarketingPropertyValue {
  Description: String
  Link: String
  LinkTitle: String
}

type Message {
  Description: String
  Operations: [ItemOperation]
  Title: String
}

enum LogicalOperator {
  And @meta(value: 0, valueType: int32)
  Or @meta(value: 1, valueType: int32)
}

type CommentContract {
  ProfilePictureThumbnailUrl: String
  ProfilePictureUrl: String
  DateCreated: Datetime
  Message: String
  Name: String
}

type Step {
  Key: String
  Value: String
}

type CultureModel {
  Name: String
  DisplayName: String
}

type SiteDataSourceConfigViewModel {
  AllowMultipleProviders: Boolean
  DependantDataSources: [String]
  IsChecked: Boolean
  Links: [SiteDataSourceLinkViewModel]
  Name: String
  SampleLink: SiteDataSourceLinkViewModel
  Title: String
}

type MarkedItem {
  ContentTypeInfo: TypeInfo
  DisplayStatus: [DisplayStatus]
  LastPublished: PublicationInfo
  LockedStatus: ItemEventInfo
  AvailableLanguages: [String]
  ContentType: String
  Id: String
  Provider: String
  Title: String
}

type TimeZoneModel {
  id: String
  name: String
}

type ParameterArgument {
  Warning: String
  AdditionalValue: String
  AdditionalValueLabel: String
  Label: String
  Value: String
}

type ServiceHookActivityDto {
  ServiceHookTitle: String
  StartTime: Datetime
  Status: ServiceHookActivityStatus
  Title: String
  TriggeredByContentItem: Boolean
  Duration: Float
  Id: String
  Result: String
  ServiceHookId: String
}

enum PageTemplateCategoryType {
  CurrentlyUsed @meta(value: 1, valueType: int32)
  None @meta(value: 0, valueType: int32)
}

enum PageType {
  Group @meta(value: 1, valueType: int32)
  Redirect @meta(value: 2, valueType: int32)
  Standard @meta(value: 0, valueType: int32)
}

type NewsItem {
  Comments: [CommentContract]
  DateCreated: Datetime
  LastModified: Datetime
  OpenGraphTitle: String
  SourceSite: String
  PublicationDate: Datetime
  Title: String
  AllowComments: Boolean
  Category: [String]
  Content: String
  Description: String
  Featured: Boolean
  UrlName: String
  Id: ID
  IncludeInSitemap: Boolean
  ItemDefaultUrl: String
  OpenGraphDescription: String
  Summary: String
  Thumbnail: Image
  Author: String
  OpenGraphImage: String
  Provider: String
  SourceName: String
  Tags: [String]
}

input NewsItemInput {
  OpenGraphTitle: String
  SourceSite: String
  Comments: [CommentContract]
  DateCreated: Datetime
  LastModified: Datetime
  Description: String
  Featured: Boolean
  PublicationDate: Datetime
  Title: String
  AllowComments: Boolean
  Category: [String]
  Content: String
  OpenGraphDescription: String
  Summary: String
  UrlName: String
  Id: String
  IncludeInSitemap: Boolean
  ItemDefaultUrl: String
  SourceName: String
  Tags: [String]
  Author: String
  OpenGraphImage: String
  Provider: String
}

type ItemOperation {
  Link: String
  Ordinal: Int
  SubOperation: ItemOperation
  ContextParameters: [OperationContextParameter]
  GroupName: String
  ExecuteOnServer: Boolean
  ParentOperation: ParentOperationInfo
  Actions: [OperationAction]
  DetailedTitle: String
  RequiresItemUpdate: Boolean
  SubText: String
  Title: String
  Warning: String
  HasLinkResult: Boolean
  KeepFocus: Boolean
  IsGroup: Boolean
  Name: String
  Parameters: [OperationParameter]
  PerformsDelete: Boolean
  RequiresConfirmation: Boolean
  Category: OperationCategory
  Description: String
}

type ItemEventInfo {
  Date: Datetime
  Id: String
  User: String
}

enum LocalizationStrategy {
  NotSelected @meta(value: 0, valueType: int32)
  Split @meta(value: 1, valueType: int32)
  Synced @meta(value: 2, valueType: int32)
}

type ComponentsResponseWithState {
  Components: [ComponentDto]
  WidgetState: [WidgetState]
}

type PageScriptAttribute {
  Key: String
  Value: String
}

type PropertiesModel {
}

type Location {
  PublicationDate: Datetime
  Id: ID
  Provider: String
  WorkingHours: String
  DateCreated: Datetime
  Phone: String
  Image: Image
  IncludeInSitemap: Boolean
  LastModified: Datetime
  Title: String
  UrlName: String
  Address: Address
  Fax: String
  Email: String
  ItemDefaultUrl: String
}

input LocationInput {
  Id: String
  Provider: String
  PublicationDate: Datetime
  DateCreated: Datetime
  Phone: String
  WorkingHours: String
  IncludeInSitemap: Boolean
  LastModified: Datetime
  Title: String
  UrlName: String
  Address: Address
  Fax: String
  Email: String
  ItemDefaultUrl: String
}

type OperationContextParameter {
  Name: String
  Value: String
}

enum PageTemplateFramework {
  Hybrid @meta(value: 0, valueType: int32)
  Mvc @meta(value: 1, valueType: int32)
  WebForms @meta(value: 2, valueType: int32)
}

type ComponentContext {
  Components: [ComponentDto]
  HasLazyComponents: Boolean
  OrphanedControls: [ComponentDto]
}

type PageTemplateCategory {
  Subtitle: String
  Templates: [Template]
  Title: String
  Type: PageTemplateCategoryType
}

type DataSourceLinkConfiguration {
  IsDefault: Boolean
  ProviderName: String
}

type ValidationContainer {
}

type AuthSettings {
  Scope: String
}

type DiagnosticResult {
  Diagnostics: [DiagnosticsDto]
}

type FrontendPageNodeExtended {
  HasChildOpen: Boolean
  IsCurrentlyOpened: Boolean
  Key: String
  LinkTarget: String
  PageSiteMapNode: FrontendSitemapPage
  Title: String
  Url: String
  ChildNodes: [FrontendPageNodeExtended]
}

type Folder {
  Provider: String
  Breadcrumb: [BreadcrumbItem]
  Description: String
  Id: ID
  LastModified: Datetime
  Title: String
  UrlName: String
  ChildrenCount: Int
  CoverId: String
  ParentId: String
  RootId: String
}

input FolderInput {
  UrlName: String
  ChildrenCount: Int
  CoverId: String
  ParentId: String
  RootId: String
  Title: String
  Breadcrumb: [BreadcrumbItem]
  Description: String
  Id: String
  LastModified: Datetime
  Provider: String
}

enum ReorderPosition {
  After @meta(value: 1, valueType: int32)
  Before @meta(value: 0, valueType: int32)
  Under @meta(value: 2, valueType: int32)
}

type Template {
  ThumbnailUrl: String
  Title: String
  UsedByNumberOfPages: Int
  Framework: PageTemplateFramework
  Id: String
  LayoutPath: String
  Name: String
  Renderer: String
}

type DataSourceConfiguration {
  IsChecked: Boolean
  Links: [DataSourceLinkConfiguration]
  Name: String
}

type ValidationErrors {
}

type Slide {
  IncludeInSitemap: Boolean
  InvertText: Boolean
  LastModified: Datetime
  UrlName: String
  PublicationDate: Datetime
  industries: [String]
  ItemDefaultUrl: String
  TextPosition: TextPosition
  Title: String
  DateCreated: Datetime
  Id: ID
  Image: Image
  Provider: String
  Subtitle: String
}

input SlideInput {
  InvertText: Boolean
  LastModified: Datetime
  UrlName: String
  IncludeInSitemap: Boolean
  industries: [String]
  PublicationDate: Datetime
  ItemDefaultUrl: String
  Id: String
  Provider: String
  Subtitle: String
  TextPosition: TextPosition
  Title: String
  DateCreated: Datetime
}

type ServiceHook {
  FailedRunsCount: Int
  Id: ID
  SuccessfulRunsCount: Int
  Title: String
  Trigger: ParameterizedSetting
  Action: ParameterizedSetting
}

input ServiceHookInput {
  Id: String
  SuccessfulRunsCount: Int
  Title: String
  Trigger: ParameterizedSetting
  Action: ParameterizedSetting
  FailedRunsCount: Int
}

type Operator {
  Key: ConditionOperator
  Value: String
}

type ParentOperationInfo {
  Required: Boolean
  Name: String
}

type Document {
  Category: [String]
  FolderId: String
  MimeType: String
  ParentId: String
  PublicationDate: Datetime
  ThumbnailUrl: String
  Image: Image
  ItemDefaultUrl: String
  Parent: DocumentLibrary
  Provider: String
  Title: String
  Url: String
  TotalSize: Int
  Author: String
  Extension: String
  Id: ID
  IncludeInSitemap: Boolean
  LastModified: Datetime
  Parts: String
  Tags: [String]
  DateCreated: Datetime
  Description: String
  Ordinal: Float
  UrlName: String
}

input DocumentInput {
  PublicationDate: Datetime
  ThumbnailUrl: String
  Category: [String]
  FolderId: String
  MimeType: String
  ParentId: String
  Title: String
  Url: String
  ItemDefaultUrl: String
  Provider: String
  LastModified: Datetime
  Parts: String
  Tags: [String]
  TotalSize: Int
  Author: String
  Extension: String
  Id: String
  IncludeInSitemap: Boolean
  DateCreated: Datetime
  Description: String
  Ordinal: Float
  UrlName: String
}

type ResolvedDetailItem {
  ErrorMessage: String
  Id: String
  ItemType: String
  ProviderName: String
}

type FieldSettingsContext {
  FieldSettings: [FieldSettings]
}

type ContentItem {
  Category: [String]
  Description: String
  LastModified: Datetime
  UrlName: String
  Content: String
  DateCreated: Datetime
  IncludeInSitemap: Boolean
  PublicationDate: Datetime
  Author: String
  Id: ID
  Provider: String
  Title: String
  Name: String
  Tags: [String]
}

input ContentItemInput {
  UrlName: String
  Content: String
  DateCreated: Datetime
  IncludeInSitemap: Boolean
  PublicationDate: Datetime
  Author: String
  Id: String
  Provider: String
  Title: String
  Name: String
  Tags: [String]
  Category: [String]
  Description: String
  LastModified: Datetime
}

type FilterItem {
  Name: String
  Parameters: FilterParameters
  Title: String
  Category: String
  Count: Int
  IsDynamicFilter: Boolean
}

enum PostRights {
  Everyone @meta(value: 1, valueType: int32)
  None @meta(value: 0, valueType: int32)
  RegisteredUsers @meta(value: 2, valueType: int32)
}

type BulkOperationResult {
  Type: BulkOperationResultType
  FailedItemsIds: [String]
  Message: String
  SucceededItemsIds: [String]
}

type SharePreviewLink {
  PreviewLink: String
  ExpirationMessage: String
}

type SortItem {
  Name: String
  Value: String
}

type PropertyContainer {
  Name: String
  Properties: PropertiesModel
  Title: String
  Type: String
  TypeChildProperties: [PropertyContainer]
  DefaultValue: String
}

type CultureViewModel {
  Key: String
  ShortName: String
  Culture: String
  FieldSuffix: String
  SitesNames: [String]
  SitesUsingCultureAsDefault: [String]
  UICulture: String
  DisplayName: String
  IsDefault: Boolean
}

enum ContentUIStatus {
  PrivateCopy @meta(value: 1, valueType: int32)
  Published @meta(value: 2, valueType: int32)
  Scheduled @meta(value: 3, valueType: int32)
  Draft @meta(value: 0, valueType: int32)
  NotSupported @meta(value: 666, valueType: int32)
}

type SharedInLocation {
  Title: String
  Url: String
  Breadcrumb: [String]
  DisplayStatus: [DisplayStatus]
  IsPage: Boolean
  SiteId: String
}

type ValidationResult {
  Errors: ValidationErrors
}

enum TextPosition {
  Left @meta(value: 1, valueType: int32)
  Right @meta(value: 2, valueType: int32)
}

