type Airline {
  AirlineCode: ID
  Name: String
}

input AirlineInput {
  AirlineCode: String
  Name: String
}

type Event {
  ConfirmationCode: String
  Description: String
  Duration: Duration
  EndsAt: Datetime
  OccursAt: EventLocation
  PlanItemId: ID
  StartsAt: Datetime
}

input EventInput {
  PlanItemId: Int
  StartsAt: Datetime
  ConfirmationCode: String
  Description: String
  Duration: Duration
  EndsAt: Datetime
  OccursAt: EventLocation
}

type Person {
  Concurrency: Int
  Emails: [String]
  FirstName: String
  Friends: [Person]
  LastName: String
  Photo: Photo
  UserName: ID
  AddressInfo: [Location]
  Trips: [Trip]
  Gender: PersonGender
}

input PersonInput {
  FirstName: String
  LastName: String
  UserName: String
  AddressInfo: [Location]
  Concurrency: Int
  Emails: [String]
  Gender: PersonGender
}

type Photo {
  Id: ID
  Name: String
}

input PhotoInput {
  Id: Int
  Name: String
}

type PlanItem {
  EndsAt: Datetime
  PlanItemId: ID
  StartsAt: Datetime
  ConfirmationCode: String
  Duration: Duration
}

input PlanItemInput {
  ConfirmationCode: String
  Duration: Duration
  EndsAt: Datetime
  PlanItemId: Int
  StartsAt: Datetime
}

type Trip {
  Budget: Float
  Description: String
  PlanItems: [PlanItem]
  ShareId: String
  Tags: [String]
  EndsAt: Datetime
  Name: String
  Photos: [Photo]
  StartsAt: Datetime
  TripId: ID
}

input TripInput {
  Budget: Float
  Description: String
  ShareId: String
  Tags: [String]
  EndsAt: Datetime
  Name: String
  StartsAt: Datetime
  TripId: Int
}

type Airport {
  Location: AirportLocation
  Name: String
  IataCode: String
  IcaoCode: ID
}

input AirportInput {
  IataCode: String
  IcaoCode: String
  Location: AirportLocation
  Name: String
}

type Flight {
  Duration: Duration
  EndsAt: Datetime
  FlightNumber: String
  From: Airport
  SeatNumber: String
  StartsAt: Datetime
  Airline: Airline
  PlanItemId: ID
  To: Airport
  ConfirmationCode: String
}

input FlightInput {
  ConfirmationCode: String
  PlanItemId: Int
  Duration: Duration
  EndsAt: Datetime
  FlightNumber: String
  SeatNumber: String
  StartsAt: Datetime
}

type PublicTransportation {
  ConfirmationCode: String
  Duration: Duration
  EndsAt: Datetime
  PlanItemId: ID
  SeatNumber: String
  StartsAt: Datetime
}

input PublicTransportationInput {
  Duration: Duration
  EndsAt: Datetime
  PlanItemId: Int
  SeatNumber: String
  StartsAt: Datetime
  ConfirmationCode: String
}

type AirportLocation {
  Loc: Geopoint
}

type City {
  CountryRegion: String
  Name: String
  Region: String
}

type EventLocation {
  BuildingInfo: String
}

type Location {
  Address: String
  City: City
}

enum PersonGender {
  Female @meta(value: 1, valueType: int32)
  Male @meta(value: 0, valueType: int32)
  Unknown @meta(value: 2, valueType: int32)
}

