type Query {
  airline(id: ID!): Airline
  airlines(filter: String, sort: String): [Airline]
  airport(id: ID!): Airport
  airports(filter: String, sort: String): [Airport]
  person(id: ID!): Person
  persons(filter: String, sort: String): [Person]
  photo(id: ID!): Photo
  photos(filter: String, sort: String): [Photo]
}

type Mutation {
  addAirline(data: AirlineInput!): Airline
  updateAirline(id: ID!, data: AirlineInput!): Boolean
  removeAirline(id: ID!): Boolean
  addAirport(data: AirportInput!): Airport
  updateAirport(id: ID!, data: AirportInput!): Boolean
  removeAirport(id: ID!): Boolean
  addPerson(data: PersonInput!): Person
  updatePerson(id: ID!, data: PersonInput!): Boolean
  removePerson(id: ID!): Boolean
  addPhoto(data: PhotoInput!): Photo
  updatePhoto(id: ID!, data: PhotoInput!): Boolean
  removePhoto(id: ID!): Boolean
}

type Airport {
  Location: AirportLocation
  Name: String
  IataCode: String
  IcaoCode: ID
}

input AirportInput {
  IataCode: String
  IcaoCode: String
  Location: AirportLocation
  Name: String
}

type City {
  Region: String
  CountryRegion: String
  Name: String
}

type Flight {
  To: Airport
  Airline: Airline
  ConfirmationCode: String
  EndsAt: Datetime
  From: Airport
  StartsAt: Datetime
  Duration: Duration
  FlightNumber: String
  PlanItemId: ID
  SeatNumber: String
}

input FlightInput {
  FlightNumber: String
  PlanItemId: Int
  SeatNumber: String
  StartsAt: Datetime
  Duration: Duration
  ConfirmationCode: String
  EndsAt: Datetime
}

type Event {
  PlanItemId: ID
  StartsAt: Datetime
  ConfirmationCode: String
  Description: String
  Duration: Duration
  EndsAt: Datetime
  OccursAt: EventLocation
}

input EventInput {
  Description: String
  Duration: Duration
  EndsAt: Datetime
  OccursAt: EventLocation
  PlanItemId: Int
  StartsAt: Datetime
  ConfirmationCode: String
}

type EventLocation {
  BuildingInfo: String
}

type PublicTransportation {
  Duration: Duration
  EndsAt: Datetime
  PlanItemId: ID
  SeatNumber: String
  StartsAt: Datetime
  ConfirmationCode: String
}

input PublicTransportationInput {
  StartsAt: Datetime
  ConfirmationCode: String
  Duration: Duration
  EndsAt: Datetime
  PlanItemId: Int
  SeatNumber: String
}

type Airline {
  AirlineCode: ID
  Name: String
}

input AirlineInput {
  AirlineCode: String
  Name: String
}

type AirportLocation {
  Loc: Geopoint
}

type Location {
  City: City
  Address: String
}

type PlanItem {
  ConfirmationCode: String
  Duration: Duration
  EndsAt: Datetime
  PlanItemId: ID
  StartsAt: Datetime
}

input PlanItemInput {
  ConfirmationCode: String
  Duration: Duration
  EndsAt: Datetime
  PlanItemId: Int
  StartsAt: Datetime
}

type Trip {
  ShareId: String
  TripId: ID
  EndsAt: Datetime
  Name: String
  Photos: [Photo]
  PlanItems: [PlanItem]
  StartsAt: Datetime
  Tags: [String]
  Budget: Float
  Description: String
}

input TripInput {
  EndsAt: Datetime
  Name: String
  ShareId: String
  TripId: Int
  StartsAt: Datetime
  Tags: [String]
  Budget: Float
  Description: String
}

type Person {
  AddressInfo: [Location]
  Concurrency: Int
  Gender: PersonGender
  Photo: Photo
  Trips: [Trip]
  Emails: [String]
  FirstName: String
  Friends: [Person]
  LastName: String
  UserName: ID
}

input PersonInput {
  Concurrency: Int
  Gender: PersonGender
  AddressInfo: [Location]
  FirstName: String
  LastName: String
  UserName: String
  Emails: [String]
}

enum PersonGender {
  Female @meta(value: 1, valueType: int32)
  Male @meta(value: 0, valueType: int32)
  Unknown @meta(value: 2, valueType: int32)
}

type Photo {
  Id: ID
  Name: String
}

input PhotoInput {
  Id: Int
  Name: String
}
